In [1]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf

In [2]:
flags = tf.app.flags
FLAGS = flags.FLAGS
flags.DEFINE_string('data_dir', './flagdata_dir/', 'Directory for storing data')

In [3]:
mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)

Extracting ./flagdata_dir/train-images-idx3-ubyte.gz
(60000, 28, 28, 1)
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]


In [4]:
print("train examples:", mnist.train.num_examples)
print("test examples:", mnist.test.num_examples)
print("validation examples:", mnist.validation.num_examples)

#print(mnist.train.images[0])

print(mnist.train.images.shape)
print(mnist.train.labels.shape)

print("num train examples:", mnist.train.num_examples)
print("num test examples:", mnist.test.num_examples)

print("Shape of training image data:", mnist.train.images.shape)
print("Shape of training label data:", mnist.train.labels.shape)

train examples: 55000
test examples: 10000
validation examples: 5000
(55000, 784)
(55000, 10)
num train examples: 55000
num test examples: 10000
Shape of training image data: (55000, 784)
Shape of training label data: (55000, 10)


In [5]:
data_sets = mnist # so we can cut/paste to and from our code

edge_labels = data_sets.train.labels.shape[1]
print(edge_labels)

print(data_sets.train.labels[0])

10
[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]


In [6]:
example_image_index = 4300
an_image = data_sets.train.images[example_image_index]
values = []
for y in range(28):
    print()
    for x in range(28):
        value = an_image[x + 28*y]
        values.append(value)
        if value > 0:
            print("1", end="")
        else:
            print("0", end="")
print("\nThe label array for this image is:", data_sets.train.labels[example_image_index])


0000000000000000000000000000
0000000000000000000000000000
0000000000000000000000000000
0000000000000000000000000000
0000001111111111110000000000
0000001111111111111000000000
0000001111100011111000000000
0000000000000001111000000000
0000000000000001111000000000
0000000000000011111000000000
0000000000001111111000000000
0000000000011111110000000000
0000000011111111100000000000
0000000011111111000000000000
0000000011111111111100000000
0000000001111111111110000000
0000000000000111111111000000
0000000000000001111111000000
0000000000000000001111000000
0000000000000000011111000000
0000000111111111111111000000
0000011111111111111111000000
0000011111111111111110000000
0000000011111111111000000000
0000000000000000000000000000
0000000000000000000000000000
0000000000000000000000000000
0000000000000000000000000000
The label array for this image is: [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]


In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.imshow(an_image)

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

In [7]:
print(values)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.18823531, 0.52549022, 0.99215692, 1.0, 0.99215692, 0.99215692, 0.99215692, 0.60000002, 0.37647063, 0.76078439, 0.37647063, 0.047058828, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.49803925, 0.98431379, 0.98431379, 0.99215692, 0.81176478, 0.24313727, 0.78823537, 0.47450984, 0.91372555, 0.98431379, 0.98431379, 0.6156863, 0.047058828, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 

In [8]:
sess = tf.InteractiveSession()

In [9]:
# Define the model
edge_labels = data_sets.train.labels.shape[1]

image_widths = 28
image_heights = 28
image_flat_size = image_widths * image_heights

print("Number of allowed num_edges (ie, size of output vector):", edge_labels)
print("Total image flat size (width * height):", image_flat_size)

Number of allowed num_edges (ie, size of output vector): 10
Total image flat size (width * height): 784


In [11]:
x = tf.placeholder(tf.float32, [None, image_flat_size])
print(x)
W = tf.Variable(tf.zeros([image_flat_size, edge_labels]))
print(W)
b = tf.Variable(tf.zeros([edge_labels]))
y = tf.nn.softmax(tf.matmul(x, W) + b)

Tensor("Placeholder_1:0", shape=(?, 784), dtype=float32)


In [15]:
# Define loss and optimizer
y_ = tf.placeholder(tf.float32, [None, edge_labels])
cross_entropy = -tf.reduce_sum(y_ * tf.log(y))
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)

In [19]:
# Train
tf.initialize_all_variables().run()
for i in range(1000):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    train_step.run({x: batch_xs, y_: batch_ys})

In [20]:
# Test trained model
correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(accuracy.eval({ x: data_sets.test.images, y_: data_sets.test.labels}))

0.912
